### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [mihailgaberov/redis-pubsub-visualized#8]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by mihailgaberov** [comment]
Hi, thank you for your interest!
This project is intended to serve demo purposes for an article I am writing about Redis Pubsub. In regards with which technology should you choose, I am not able to recommend you one or another, as it's all depends on your project's needs and requirements. I am sure you may find a lot of comparison between them online and this will help more to decide. 

I am holding off the publishing of the article for now, as I am trying to find a free onlime solution for deploying the demo and see it in action. Once I do that, I will publish the article on my blog and post a link in the project's README as well.

I hope that helps you a bit. Good luck with your project! 🍀
